NO-JIRA: tests(gha): add `check-payload` integration and dependency management
Introduce the `check-payload` tool for image vulnerability scanning. Updated workflows to cache Go module dependencies and run the `check-payload` scan, ensuring it doesn't fail the build by default.

Added Go module files for managing dependencies of the new tooling.

diff --git a/.github/workflows/build-notebooks-TEMPLATE.yaml b/.github/workflows/build-notebooks-TEMPLATE.yaml
--- a/.github/workflows/build-notebooks-TEMPLATE.yaml
+++ b/.github/workflows/build-notebooks-TEMPLATE.yaml
@@ -86,7 +86,7 @@ jobs:
       # for bin/buildinputs in scripts/sandbox.py
       - uses: actions/setup-go@v5
         with:
-          cache-dependency-path: "**/*.sum"
+          cache-dependency-path: "scripts/buildinputs/go.sum"
 
       - run: sudo apt-get update
 
@@ -558,6 +558,45 @@ jobs:
                 $SCAN_TARGET
 
           cat $REPORT_FOLDER/$REPORT_FILE >> $GITHUB_STEP_SUMMARY
+
+      # endregion
+
+      # region Trivy vulnerability scan
+
+      - id: check-payload-vars
+        run: |
+          echo "GOPATH=${{ github.workspace }}/go-check-payload" >> "$GITHUB_OUTPUT"
+        working-directory: scripts/check-payload
+
+      # for https://github.com/openshift/check-payload to cache the built binary
+      - uses: actions/setup-go@v5
+        with:
+          cache-dependency-path: "scripts/check-payload/go.sum"
+        env:
+          GOPATH: ${{ steps.check-payload-vars.outputs.GOPATH }}
+
+      # F0512 15:43:03.219076 21568 main.go:294] Error: exec: "oc": executable file not found in $PATH
+      - name: Install oc client
+        run: |
+          # Install the oc client
+          curl -L https://mirror.openshift.com/pub/openshift-v4/$(uname -m)/clients/ocp/stable/openshift-client-linux.tar.gz -o /tmp/openshift-client-linux.tar.gz
+          tar -xzvf /tmp/openshift-client-linux.tar.gz oc
+          rm -f /tmp/openshift-client-linux.tar.gz
+          sudo mv ./oc /usr/local/bin
+
+      # use sudo to avoid
+      #  podman error (args=[image mount ghcr.io/...])
+      #  (stderr=Error: cannot use command "podman image mount" with the remote podman client
+      # and use --preserve-env=PATH to avoid
+      #  F0512 16:31:58.425584    9911 main.go:294] Error: exec: "podman": executable file not found in $PATH
+      - name: Check image with check-payload
+        run: |
+          set -Eeuxo pipefail
+          # don't fail the build if the check fails, at least for now
+          sudo --preserve-env=PATH go run github.com/openshift/check-payload scan image --spec "${{ steps.calculated_vars.outputs.OUTPUT_IMAGE }}" || true
+        working-directory: scripts/check-payload
+        env:
+          GOPATH: ${{ steps.check-payload-vars.outputs.GOPATH }}
 
       # endregion
 
